"""
City Service
Handles city data operations using offline JSON data.

Data Source: GeoNames cities15000 (cities with population > 15000)
Generated by: scripts/import_cities.py
"""
import json
import logging
from pathlib import Path
from typing import Dict, Any, Optional, List

logger = logging.getLogger(__name__)
logger.setLevel(logging.WARNING)


class CityService:
    """Service for city data operations."""
    
    _instance = None
    _initialized = False
    
    def __new__(cls):
        if cls._instance is None:
            cls._instance = super().__new__(cls)
        return cls._instance
    
    def __init__(self):
        if CityService._initialized:
            return
        
        self.countries_data: Dict[str, Any] = {}
        self.cities_data: Dict[str, Any] = {}
        self._load_data()
        CityService._initialized = True
    
    def _load_data(self):
        """Load countries and cities data from JSON files."""
        data_dir = Path(__file__).parent.parent.parent / "data"
        
        # Load countries
        countries_file = data_dir / "countries.json"
        if countries_file.exists():
            try:
                with open(countries_file, 'r', encoding='utf-8') as f:
                    self.countries_data = json.load(f)
                logger.info(f"Loaded {len(self.countries_data)} countries from {countries_file}")
            except Exception as e:
                logger.error(f"Failed to load countries: {e}")
        else:
            logger.warning(f"Countries file not found: {countries_file}")
        
        # Load cities
        cities_file = data_dir / "cities.json"
        if cities_file.exists():
            try:
                with open(cities_file, 'r', encoding='utf-8') as f:
                    self.cities_data = json.load(f)
                logger.info(f"Loaded cities for {len(self.cities_data)} countries from {cities_file}")
            except Exception as e:
                logger.error(f"Failed to load cities: {e}")
        else:
            logger.warning(f"Cities file not found: {cities_file}")
    
    def get_countries(self) -> List[str]:
        """Get list of available countries sorted alphabetically."""
        return sorted(self.cities_data.keys())
    
    def get_country_code(self, country: str) -> Optional[str]:
        """Get country code for a country name."""
        if country in self.cities_data:
            return self.cities_data[country].get("code")
        return None
    
    def get_cities_for_country(self, country: str) -> List[Dict[str, Any]]:
        """Get list of cities for a country."""
        if country not in self.cities_data:
            return []
        
        country_data = self.cities_data[country]
        cities = country_data.get("cities", [])
        return sorted(cities, key=lambda x: x["name"])
    
    def get_city_names_for_country(self, country: str) -> List[str]:
        """Get list of city names for a country."""
        cities = self.get_cities_for_country(country)
        return [city["name"] for city in cities]
    
    def get_city_data(self, country: str, city_name: str) -> Optional[Dict[str, Any]]:
        """Get data for a specific city."""
        if country not in self.cities_data:
            return None
        
        cities = self.cities_data[country].get("cities", [])
        for city in cities:
            if city["name"] == city_name:
                return {
                    "lat": city["lat"],
                    "lon": city["lon"],
                    "timezone": city["timezone"]
                }
        return None
    
    def find_closest_city(self, lat: float, lon: float) -> Optional[Dict[str, Any]]:
        """Find the closest city from our database to the given coordinates."""
        if lat == 0 and lon == 0:
            return None
        
        min_distance = float('inf')
        closest = None
        
        for country, country_data in self.cities_data.items():
            for city in country_data.get("cities", []):
                city_lat = city["lat"]
                city_lon = city["lon"]
                
                # Calculate simple distance (Euclidean approximation)
                distance = ((lat - city_lat) ** 2 + (lon - city_lon) ** 2) ** 0.5
                
                if distance < min_distance:
                    min_distance = distance
                    closest = {
                        "city": city["name"],
                        "country": country,
                        "lat": city_lat,
                        "lon": city_lon,
                        "timezone": city["timezone"]
                    }
        
        return closest
    
    def find_city_by_timezone(self, timezone: str) -> Optional[Dict[str, Any]]:
        """Find a city matching the given timezone."""
        for country, country_data in self.cities_data.items():
            for city in country_data.get("cities", []):
                if city["timezone"] == timezone:
                    return {
                        "city": city["name"],
                        "country": country,
                        "lat": city["lat"],
                        "lon": city["lon"],
                        "timezone": city["timezone"]
                    }
        return None
    
    def search_cities(self, query: str, limit: int = 20) -> List[Dict[str, Any]]:
        """Search for cities by name."""
        query_lower = query.lower()
        results = []
        
        for country, country_data in self.cities_data.items():
            for city in country_data.get("cities", []):
                if query_lower in city["name"].lower():
                    results.append({
                        "city": city["name"],
                        "country": country,
                        "lat": city["lat"],
                        "lon": city["lon"],
                        "timezone": city["timezone"]
                    })
                    
                    if len(results) >= limit:
                        return results
        
        return results
    
    def get_all_data(self) -> Dict[str, Any]:
        """Get all countries, cities data for initial load."""
        return {
            "countries": self.get_countries(),
            "cities_data": self.cities_data
        }


# Singleton instance
city_service = CityService()
